base_config: src/configs/main_base_rsa_config.yaml
this_output_dir: src/configs
results_and_analysis_output_dir: data/prag_mega_plus_exps/results_and_analysis
gen_llm: llama_8b
prob_llm: mistral_7b_instruct
extra_details: main_paper
base_config_common_keys:
  dataset_name: prag_mega_test_split
  dataset_path: data/exp_data/prag_mega_plus/ScenariosCombinedDiversified.csv
  alt_utterances_path: null
  llm_probs_path: null
  output_dir: data/prag_mega_plus_exps/rsa_runs
prior_ablations:
  - unchanged
  - no_p_m_c
  - no_p_r_c_u
  - no_p_u_c