hydra:
  sweep:
    dir: /home/mila/c/cesare.spinoso/SarcRSA/datasets/hydra
    subdir: ${hydra.job.override_dirname}
  output_subdir: null
prior_path: "data/exp_data/ironic_weather_utterances/priors/long.csv"
interpretation_w_irony_path: "data/exp_data/ironic_weather_utterances/interpretation/long_askIrony.csv"
train_network: false
architecture: "rs x c x u -> linear -> sigmoid -> linear -> sigmoid -> m"
seed: 42
weight_decay: 0.001
lr: 0.001
epochs: 500
p_quds: # using the values from the Kao paper
  q_state: 0.3
  q_valence: 0.3
  q_arousal: 0.4
output_dir: data/ironic_weather_utterances_exps
